{% set name = "html-sanitizer" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/html_sanitizer-{{ version }}.tar.gz
  sha256: 34d1dfad0cf7663022864521425dcbeaca3ddcca16daa06b1e4325e5347368db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - lxml >=4.9.1

test:
  imports:
    - html_sanitizer
  commands:
    - pip check
  requires:
    - pip

about:
  summary: HTML sanitizer
  home: https://github.com/matthiask/html-sanitizer/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
