{% set name = "html-sanitizer" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/html_sanitizer-{{ version }}.tar.gz
  sha256: 8878c2383070e8a5023814d621e4133d15f8c013ec9a5619be280739d56d6ec5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - lxml >=5.2
    - lxml-html-clean >=0.1

test:
  imports:
    - html_sanitizer
  commands:
    - pip check
  requires:
    - pip

about:
  summary: HTML sanitizer
  home: https://github.com/matthiask/html-sanitizer/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
